-- begin CUBATEST_PRODUCT_OFFERING
alter table CUBATEST_PRODUCT_OFFERING add constraint FK_CUBATEST_PROOFF_ON_CHARS1 foreign key (CHARS_ID) references SEC_ROLE(ID)^
create index IDX_CUBATEST_PROOFF_ON_CHARS1 on CUBATEST_PRODUCT_OFFERING (CHARS_ID)^
create index IDX_CUBATEST_PRODUCT_OFFERING on CUBATEST_PRODUCT_OFFERING (NAME) ^
-- end CUBATEST_PRODUCT_OFFERING
-- begin PRODUCT_OFFERINGS
alter table PRODUCT_OFFERINGS add constraint FK_PRODUCT_OFFE_ON_PRCT_PRCT foreign key (PRCT_PRCT_ID) references PRODUCT_CATEGORIES(PRCT_ID)^
alter table PRODUCT_OFFERINGS add constraint FK_PRODUCT_OFF_ON_TEROCCPER foreign key (TERM_OCC_PERMU_ID) references PERIOD_MEASURE_UNITS(PERMU_ID)^
alter table PRODUCT_OFFERINGS add constraint FK_PRODUCT_OFFE_ON_PRLN_PRLN foreign key (PRLN_PRLN_ID) references PRODUCT_LINES(PRLN_ID)^
alter table PRODUCT_OFFERINGS add constraint FK_PRODUCT_OFFE_ON_PRSP_PRSP foreign key (PRSP_PRSP_ID) references PRODUCT_SPECIFICATIONS(PRSP_ID)^
alter table PRODUCT_OFFERINGS add constraint FK_PRODUCT_OFFE_ON_CLASCLAS foreign key (CLASS_CLASS_ID) references CLASSES(CLASS_ID)^
alter table PRODUCT_OFFERINGS add constraint FK_PRODUCT_OF_ON_TEPRDUPE foreign key (TERM_PROD_DUR_PERMU_ID) references PERIOD_MEASURE_UNITS(PERMU_ID)^
alter table PRODUCT_OFFERINGS add constraint FK_PRODUCT_OFFE_ON_PRTP_PRTP foreign key (PRTP_PRTP_ID) references PRODUCT_TYPES(PRTP_ID)^
create index IDX_PRODUCT_OFF_ON_PRCT_PRCT on PRODUCT_OFFERINGS (PRCT_PRCT_ID)^
create index IDX_PRODUCT_OFF_ON_TEROCCPER on PRODUCT_OFFERINGS (TERM_OCC_PERMU_ID)^
create index IDX_PRODUCT_OFF_ON_PRLN_PRLN on PRODUCT_OFFERINGS (PRLN_PRLN_ID)^
create index IDX_PRODUCT_OFF_ON_PRSP_PRSP on PRODUCT_OFFERINGS (PRSP_PRSP_ID)^
create index IDX_PRODUCT_OFF_ON_CLACLA1 on PRODUCT_OFFERINGS (CLASS_CLASS_ID)^
create index IDX_PRODUCT_OF_ON_TEPRDUPE on PRODUCT_OFFERINGS (TERM_PROD_DUR_PERMU_ID)^
create index IDX_PRODUCT_OFF_ON_PRTP_PRTP1 on PRODUCT_OFFERINGS (PRTP_PRTP_ID)^
-- end PRODUCT_OFFERINGS
-- begin PRODUCT_SPECIFICATIONS
alter table PRODUCT_SPECIFICATIONS add constraint FK_PRODUCT_SPEC_ON_PAREPRSP foreign key (PARENT_PRSP_ID) references PRODUCT_SPECIFICATIONS(PRSP_ID)^
alter table PRODUCT_SPECIFICATIONS add constraint FK_PRODUCT_SPEC_ON_CLASCLAS foreign key (CLASS_CLASS_ID) references CLASSES(CLASS_ID)^
create index IDX_PRODUCT_SPE_ON_PARPRS on PRODUCT_SPECIFICATIONS (PARENT_PRSP_ID)^
create index IDX_PRODUCT_SPE_ON_CLACLA1 on PRODUCT_SPECIFICATIONS (CLASS_CLASS_ID)^
-- end PRODUCT_SPECIFICATIONS
-- begin EMBEDDED_PRODUCT_OFFERINGS
alter table EMBEDDED_PRODUCT_OFFERINGS add constraint FK_EMBEDDED_PROOFF_ON_PARPRO foreign key (PARENT_PROF_ID) references PRODUCT_OFFERINGS(PROF_ID)^
alter table EMBEDDED_PRODUCT_OFFERINGS add constraint FK_EMBEDDED_PROOFF_ON_CHIPRO foreign key (CHILD_PROF_ID) references PRODUCT_OFFERINGS(PROF_ID)^
create index IDX_EMBEDDED_PROF_ON_PAPR on EMBEDDED_PRODUCT_OFFERINGS (PARENT_PROF_ID)^
create index IDX_EMBEDDED_PROF_ON_CHPR on EMBEDDED_PRODUCT_OFFERINGS (CHILD_PROF_ID)^
-- end EMBEDDED_PRODUCT_OFFERINGS
