alter table CUBATEST_PRODUCT_OFFERING add constraint FK_CUBATEST_PROOFF_ON_CHARS foreign key (CHARS_ID) references SEC_ROLE(ID)^
create index IDX_CUBATEST_PROOFF_ON_CHARS on CUBATEST_PRODUCT_OFFERING (CHARS_ID)^
